import React from 'react';
import { Metadata } from 'next';
import LegalPage from '@/components/LegalPage';
import { companyDetails } from '@/data/companyDetails';

export const metadata: Metadata = {
  title: 'End User License Agreement (EULA) | OpsCel',
  description: 'End User License Agreement for OpsCel job management software. Read our terms for subscription, data ownership, and acceptable use.',
};

const EULAPage: React.FC = () => {
  return (
    <LegalPage
      title="End User License Agreement"
      lastUpdated="24 May 2026"
    >
      {/* Plain-English Summary */}
      <div className="bg-blue-50 border-l-4 border-blue-500 p-6 mb-8 rounded-r-lg">
        <h2 className="text-xl font-heading font-bold text-blue-900 mb-3">Plain-English Summary</h2>
        <p className="text-blue-800 mb-3">
          This agreement covers your use of OpsCel software. Key points:
        </p>
        <ul className="list-disc list-inside space-y-2 text-blue-800 ml-4">
          <li><strong>You own your data</strong> — we never sell it or use it for other customers</li>
          <li><strong>Pay monthly</strong> — 90-day free trial, cancel anytime</li>
          <li><strong>UK-based</strong> — your data stays in UK data centres, governed by English law</li>
          <li><strong>Acceptable use</strong> — use it legally, don&apos;t abuse the service</li>
          <li><strong>AI features</strong> — we use your data to provide AI services (like auto-fill), but it&apos;s private to you</li>
          <li><strong>Third-party integrations</strong> — Xero, Telegram, calendars have their own terms</li>
        </ul>
        <p className="text-blue-800 mt-3 text-sm italic">
          This summary is for convenience only. The full legal terms below are binding.
        </p>
      </div>

      {/* Important Notice */}
      <div className="bg-amber-50 border-l-4 border-amber-500 p-6 mb-8 rounded-r-lg">
        <p className="text-amber-900 font-semibold mb-2">⚠️ Important Legal Notice</p>
        <p className="text-amber-800">
          This End User License Agreement (&quot;EULA&quot;) is a legal contract between you (either an individual or a single entity, referred to as &quot;Customer&quot;, &quot;you&quot;, or &quot;your&quot;) and Opscel Ltd (Company Number {companyDetails.companiesHouseNumber}, registered in England and Wales) (&quot;OpsCel&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) for the use of the OpsCel software-as-a-service platform.
        </p>
        <p className="text-amber-800 mt-3">
          <strong>By creating an account, accessing, or using OpsCel, you agree to be bound by this EULA.</strong> If you do not agree, do not use the service.
        </p>
      </div>

      {/* 1. Definitions */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">1. Definitions</h2>

        <div className="space-y-3 text-foreground-accent">
          <p><strong>&quot;Service&quot;</strong> means the OpsCel web application, mobile progressive web app (PWA), and all related software, APIs, documentation, and updates provided by OpsCel.</p>

          <p><strong>&quot;Customer Data&quot;</strong> means all data, content, and information submitted, uploaded, or generated by you or your users through the Service, including but not limited to customer records, job details, certificates, invoices, quotes, photos, and field notes.</p>

          <p><strong>&quot;Subscription&quot;</strong> means a paid or trial subscription to access and use the Service under a specific pricing tier (Starter, Team, or Business).</p>

          <p><strong>&quot;Account&quot;</strong> means your unique tenant account created to access the Service, including all user accounts and data associated with your business.</p>

          <p><strong>&quot;User&quot;</strong> means any individual authorised by you to access the Service under your Account (e.g., engineers, administrators, office staff).</p>

          <p><strong>&quot;Third-Party Services&quot;</strong> means external services integrated with OpsCel, including Xero, QuickBooks, Telegram, Google Calendar, Microsoft 365, and other calendar providers.</p>
        </div>
      </section>

      {/* 2. License Grant */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">2. License Grant</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> We give you permission to use OpsCel for your business. You can&apos;t sell it, copy it, or let others use your account.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>2.1 Grant of License:</strong> Subject to your compliance with this EULA and payment of applicable fees, OpsCel grants you a non-exclusive, non-transferable, revocable license to access and use the Service during the Subscription term solely for your internal business operations.
          </p>

          <p>
            <strong>2.2 License Restrictions:</strong> You agree NOT to:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>Copy, modify, distribute, sell, or lease any part of the Service</li>
            <li>Reverse engineer, decompile, or attempt to extract source code from the Service</li>
            <li>Remove or alter any proprietary notices, labels, or marks</li>
            <li>Use the Service to provide services to third parties (no white-labeling or reselling)</li>
            <li>Access the Service to build a competitive product or service</li>
            <li>Circumvent usage limits, authentication mechanisms, or security measures</li>
            <li>Use automated tools (bots, scrapers) to access the Service without written permission</li>
          </ul>

          <p>
            <strong>2.3 User Accounts:</strong> You are responsible for all activity under your Account. You must maintain the confidentiality of login credentials and notify us immediately of any unauthorised access at <a href="mailto:support@opscel.com" className="text-secondary hover:underline">support@opscel.com</a>.
          </p>
        </div>
      </section>

      {/* 3. Subscription & Payment */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">3. Subscription & Payment</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> You pay monthly. 90-day free trial included. Cancel anytime. Prices may change with 30 days notice.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>3.1 Free Trial:</strong> New customers receive a 90-day free trial with full access to features on their selected plan. A valid payment method is required to start the trial. You will be charged automatically at the end of the trial unless you cancel.
          </p>

          <p>
            <strong>3.2 Subscription Fees:</strong> After the trial, Subscriptions are billed monthly in advance. Current pricing is available at <a href="https://www.opscel.com/#pricing" className="text-secondary hover:underline">www.opscel.com/#pricing</a>. All fees are non-refundable except as required by law.
          </p>

          <p>
            <strong>3.3 Payment Terms:</strong> You authorise OpsCel to charge your payment method on file each billing cycle. If payment fails, we will notify you and may suspend access until payment is resolved. Continued failure to pay may result in account termination.
          </p>

          <p>
            <strong>3.4 Price Changes:</strong> We may change Subscription prices with at least 30 days&apos; advance notice. Price changes apply to the next billing cycle after notice. Continued use after a price change constitutes acceptance.
          </p>

          <p>
            <strong>3.5 Taxes:</strong> All fees exclude VAT and other applicable taxes. You are responsible for all taxes associated with your Subscription. We will add VAT to invoices where required by UK law.
          </p>
        </div>
      </section>

      {/* 4. Data Ownership & Privacy */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">4. Data Ownership & Privacy</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> You own your data. We store it securely in UK data centres. We don&apos;t sell it or share it with other customers. See our Privacy Policy for details.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>4.1 Customer Data Ownership:</strong> You retain all rights, title, and interest in and to your Customer Data. OpsCel claims no ownership rights to your Customer Data.
          </p>

          <p>
            <strong>4.2 Data Isolation:</strong> OpsCel operates a multi-tenant SaaS platform with row-level security. Your Customer Data is logically isolated from other customers and is never accessible to other tenants.
          </p>

          <p>
            <strong>4.3 Data Location:</strong> All Customer Data is stored in UK-based data centres. Data does not leave the United Kingdom unless you explicitly use export features or integrate with Third-Party Services hosted outside the UK.
          </p>

          <p>
            <strong>4.4 Data Processing:</strong> OpsCel processes your Customer Data solely to provide the Service. We do not sell, rent, or share your Customer Data with third parties for marketing purposes.
          </p>

          <p>
            <strong>4.5 GDPR Compliance:</strong> OpsCel complies with the UK General Data Protection Regulation (UK GDPR) and Data Protection Act 2018. Our Privacy Policy (available at <a href="https://www.opscel.com/privacy" className="text-secondary hover:underline">www.opscel.com/privacy</a>) explains how we process personal data. For data processing questions, contact <a href="mailto:privacy@opscel.com" className="text-secondary hover:underline">privacy@opscel.com</a>.
          </p>

          <p>
            <strong>4.6 Data Backup:</strong> OpsCel performs regular backups of Customer Data. However, you are responsible for maintaining your own backup copies of critical data.
          </p>

          <p>
            <strong>4.7 Data Deletion:</strong> Upon account termination or cancellation, your Customer Data will be retained for 30 days to allow account reinstatement. After 30 days, all Customer Data is permanently deleted from production systems. Backup copies may persist for up to 90 days.
          </p>
        </div>
      </section>

      {/* 5. AI & Machine Learning */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">5. AI & Machine Learning Features</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> OpsCel uses AI to auto-fill forms, validate certificates, and improve features. Your data trains AI models for YOUR account only — we never use your data to improve other customers&apos; AI.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>5.1 AI-Powered Features:</strong> The Service includes AI-assisted features such as data auto-fill, certificate validation, defect classification, and predictive scheduling. These features use machine learning models trained on industry standards (e.g., BS 7671, BS 5839) and your historical data.
          </p>

          <p>
            <strong>5.2 Data Usage for AI:</strong> OpsCel may use your Customer Data to train and improve AI models that serve YOUR Account only. Your data is NOT used to train models for other customers. AI models are tenant-specific and isolated.
          </p>

          <p>
            <strong>5.3 AI Accuracy:</strong> While OpsCel&apos;s AI features are designed to improve accuracy and efficiency, they are not infallible. You remain responsible for reviewing and verifying all AI-generated suggestions, classifications, and validations before relying on them.
          </p>

          <p>
            <strong>5.4 No Liability for AI Errors:</strong> OpsCel is not liable for errors, omissions, or inaccuracies in AI-generated content. Always verify critical information (e.g., Zs limits, certificate validation) against official standards.
          </p>
        </div>
      </section>

      {/* 6. Third-Party Integrations */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">6. Third-Party Integrations</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> OpsCel connects to Xero, Telegram, and calendars. Those services have their own terms. We&apos;re not responsible if they break or change.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>6.1 Integrated Services:</strong> OpsCel integrates with Third-Party Services including:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li><strong>Xero</strong> — accounting integration for invoicing and payment sync</li>
            <li><strong>QuickBooks</strong> — accounting integration (planned)</li>
            <li><strong>Telegram</strong> — instant notifications via Telegram bot</li>
            <li><strong>Google Calendar, Microsoft 365, ICS feeds</strong> — calendar sync for job scheduling</li>
          </ul>

          <p>
            <strong>6.2 Third-Party Terms:</strong> Your use of Third-Party Services is governed by their respective terms of service and privacy policies. OpsCel is not responsible for Third-Party Services&apos; availability, functionality, or data handling practices.
          </p>

          <p>
            <strong>6.3 Data Sharing:</strong> When you connect a Third-Party Service, you authorise OpsCel to share relevant data (e.g., invoices to Xero, job notifications to Telegram) with that service. Data shared with Third-Party Services is subject to their privacy policies.
          </p>

          <p>
            <strong>6.4 Integration Changes:</strong> OpsCel may add, modify, or discontinue Third-Party Integrations at any time. We are not liable for changes to or discontinuation of Third-Party Services.
          </p>

          <p>
            <strong>6.5 OAuth Tokens:</strong> Third-Party Integrations use OAuth for secure authentication. You may revoke access at any time through the Service settings or the Third-Party Service&apos;s account management.
          </p>
        </div>
      </section>

      {/* 7. Mobile PWA */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">7. Mobile Progressive Web App (PWA)</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> The mobile field app works offline. Data syncs when you&apos;re back online. You&apos;re responsible for device security and network charges.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>7.1 PWA Access:</strong> OpsCel provides a Progressive Web App (PWA) for iOS, Android, and desktop browsers. The PWA offers offline functionality for field engineers, including job access, photo capture, form completion, and data logging.
          </p>

          <p>
            <strong>7.2 Offline Mode:</strong> The PWA caches data locally on your device to enable offline use. Changes made offline are queued and sync automatically when an internet connection is restored. OpsCel is not liable for data loss if your device is lost, stolen, or damaged before sync completes.
          </p>

          <p>
            <strong>7.3 Device Requirements:</strong> The PWA requires a modern web browser (Chrome, Safari, Edge, or Firefox) and sufficient device storage. OpsCel does not guarantee compatibility with all devices or operating system versions.
          </p>

          <p>
            <strong>7.4 Network Charges:</strong> You are responsible for all network charges (data, Wi-Fi, mobile) incurred while using the Service. OpsCel recommends using Wi-Fi for large uploads (photos, PDFs) to avoid excessive mobile data charges.
          </p>

          <p>
            <strong>7.5 Device Security:</strong> You are responsible for securing devices used to access the Service. Use device passwords, biometric locks, and remote wipe features where available. Notify us immediately if a device with access to OpsCel is lost or stolen.
          </p>
        </div>
      </section>

      {/* 8. Beta Features */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">8. Beta Features & Experimental Functionality</h2>

        <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg mb-4">
          <p className="text-amber-800">
            <strong>⚠️ Beta Disclaimer:</strong> Features marked as &quot;Beta&quot;, &quot;Preview&quot;, or &quot;Experimental&quot; are provided AS-IS without warranty. They may change or be discontinued at any time.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>8.1 Beta Participation:</strong> OpsCel may release features in beta or preview status to gather customer feedback before general availability. Beta features are clearly labelled in the Service.
          </p>

          <p>
            <strong>8.2 No Warranty:</strong> Beta features are provided &quot;AS-IS&quot; without warranties of any kind. OpsCel makes no guarantees regarding beta feature availability, performance, or data integrity. Use beta features at your own risk.
          </p>

          <p>
            <strong>8.3 Changes & Discontinuation:</strong> OpsCel may modify, limit, or discontinue beta features at any time without notice. Data created using beta features may not be compatible with future versions.
          </p>

          <p>
            <strong>8.4 Feedback:</strong> If you provide feedback on beta features, you grant OpsCel a perpetual, royalty-free license to use that feedback to improve the Service.
          </p>
        </div>
      </section>

      {/* 9. Acceptable Use Policy */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">9. Acceptable Use Policy</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> Use OpsCel legally. Don&apos;t hack it, abuse it, or use it for illegal purposes. We&apos;ll suspend your account if you do.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>9.1 Prohibited Activities:</strong> You agree NOT to use the Service to:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>Violate any laws, regulations, or third-party rights</li>
            <li>Transmit viruses, malware, or malicious code</li>
            <li>Harass, abuse, threaten, or intimidate others</li>
            <li>Impersonate any person or entity</li>
            <li>Interfere with or disrupt the Service or servers</li>
            <li>Attempt unauthorised access to other customers&apos; accounts or data</li>
            <li>Upload illegal, infringing, defamatory, or obscene content</li>
            <li>Generate excessive load through automated means (spam, denial-of-service attacks)</li>
            <li>Use the Service for cryptocurrency mining, proxy services, or other resource-intensive non-business purposes</li>
          </ul>

          <p>
            <strong>9.2 Content Standards:</strong> You are responsible for ensuring that all Customer Data complies with applicable laws, including but not limited to data protection, intellectual property, and industry regulations (e.g., BS 7671, BS 5839).
          </p>

          <p>
            <strong>9.3 Enforcement:</strong> OpsCel reserves the right to investigate violations of this Acceptable Use Policy. We may suspend or terminate accounts that violate this policy, with or without notice, and without refund.
          </p>
        </div>
      </section>

      {/* 10. Service Availability */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">10. Service Availability & Support</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> We aim for high uptime but can&apos;t guarantee 100%. Scheduled maintenance happens occasionally. Check status.opscel.com for real-time status.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>10.1 Uptime Commitment:</strong> OpsCel strives to maintain high Service availability but does not guarantee 100% uptime. Scheduled maintenance, security updates, and unplanned outages may occur.
          </p>

          <p>
            <strong>10.2 Scheduled Maintenance:</strong> We perform scheduled maintenance during off-peak hours (typically 01:00-05:00 GMT) with advance notice via email and the Service dashboard. Emergency maintenance may occur without notice.
          </p>

          <p>
            <strong>10.3 Status Updates:</strong> Real-time Service status is available at <a href="https://status.opscel.com" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">status.opscel.com</a>.
          </p>

          <p>
            <strong>10.4 Support:</strong> Email support is available at <a href="mailto:support@opscel.com" className="text-secondary hover:underline">support@opscel.com</a>. Response times vary by plan tier. Documentation is available at <a href="https://www.opscel.com/docs" className="text-secondary hover:underline">www.opscel.com/docs</a> and <a href="https://help.opscel.com" target="_blank" rel="noopener noreferrer" className="text-secondary hover:underline">help.opscel.com</a>.
          </p>

          <p>
            <strong>10.5 Service Changes:</strong> OpsCel may modify, update, or discontinue features at any time. We will provide reasonable notice of material changes that negatively affect functionality.
          </p>
        </div>
      </section>

      {/* 11. Intellectual Property */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">11. Intellectual Property Rights</h2>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>11.1 OpsCel IP:</strong> The Service, including all software, code, design, logos, trademarks, documentation, and branding, is the exclusive property of OpsCel and is protected by UK and international intellectual property laws.
          </p>

          <p>
            <strong>11.2 Trademarks:</strong> &quot;OpsCel&quot;, the OpsCel logo, and related marks are trademarks of Opscel Ltd. You may not use these marks without prior written permission.
          </p>

          <p>
            <strong>11.3 Customer Data IP:</strong> You retain all intellectual property rights in your Customer Data. By using the Service, you grant OpsCel a limited license to host, process, and display your Customer Data solely to provide the Service.
          </p>

          <p>
            <strong>11.4 Feedback License:</strong> If you provide suggestions, ideas, or feedback about the Service, you grant OpsCel a perpetual, worldwide, royalty-free license to use, incorporate, and commercialise that feedback without compensation or attribution.
          </p>
        </div>
      </section>

      {/* 12. Term & Termination */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">12. Term & Termination</h2>

        <div className="bg-muted p-4 rounded-lg mb-4">
          <p className="text-sm text-muted-foreground italic">
            <strong>In plain English:</strong> Cancel anytime from your account settings. We can terminate for policy violations. Your data is available for 30 days after cancellation.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>12.1 Subscription Term:</strong> Subscriptions continue on a monthly rolling basis until cancelled by you or terminated by OpsCel.
          </p>

          <p>
            <strong>12.2 Cancellation by Customer:</strong> You may cancel your Subscription at any time through your Account settings or by contacting <a href="mailto:support@opscel.com" className="text-secondary hover:underline">support@opscel.com</a>. Cancellation takes effect at the end of the current billing cycle. No refunds are provided for partial months.
          </p>

          <p>
            <strong>12.3 Termination by OpsCel:</strong> OpsCel may suspend or terminate your Account immediately if you:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>Breach this EULA or the Acceptable Use Policy</li>
            <li>Fail to pay fees for 15 days after notice</li>
            <li>Engage in fraudulent or illegal activity</li>
            <li>Pose a security risk to the Service or other customers</li>
          </ul>

          <p>
            <strong>12.4 Effect of Termination:</strong> Upon termination or cancellation:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>Your license to use the Service immediately terminates</li>
            <li>Access to your Account and Customer Data is suspended</li>
            <li>Customer Data is retained for 30 days to allow account reinstatement</li>
            <li>After 30 days, all Customer Data is permanently deleted</li>
            <li>You may request a data export before deletion by contacting <a href="mailto:support@opscel.com" className="text-secondary hover:underline">support@opscel.com</a></li>
          </ul>

          <p>
            <strong>12.5 Survival:</strong> Sections 4 (Data Ownership), 11 (Intellectual Property), 13 (Limitation of Liability), 14 (Indemnification), and 15 (Governing Law) survive termination.
          </p>
        </div>
      </section>

      {/* 13. Limitation of Liability */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">13. Limitation of Liability & Disclaimers</h2>

        <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg mb-4">
          <p className="text-amber-800">
            <strong>⚠️ Important:</strong> OpsCel provides the Service &quot;as-is&quot;. We limit our liability to the maximum extent permitted by law.
          </p>
        </div>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>13.1 No Warranties:</strong> THE SERVICE IS PROVIDED &quot;AS-IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
          </p>

          <p>
            <strong>13.2 No Guarantee:</strong> OpsCel does not warrant that:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>The Service will be uninterrupted, error-free, or secure</li>
            <li>Defects will be corrected</li>
            <li>The Service will meet your specific requirements</li>
            <li>AI-generated content will be accurate or reliable</li>
            <li>Third-Party Integrations will remain available or functional</li>
          </ul>

          <p>
            <strong>13.3 Limitation of Liability:</strong> TO THE FULLEST EXTENT PERMITTED BY LAW, OPSCEL&apos;S TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM THIS EULA OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO OPSCEL IN THE 12 MONTHS PRECEDING THE CLAIM.
          </p>

          <p>
            <strong>13.4 Exclusion of Damages:</strong> IN NO EVENT SHALL OPSCEL BE LIABLE FOR:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>LOSS OF PROFITS, REVENUE, DATA, OR BUSINESS OPPORTUNITIES</li>
            <li>INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE DAMAGES</li>
            <li>DAMAGES ARISING FROM DATA BREACHES, SERVICE OUTAGES, OR THIRD-PARTY ACTIONS</li>
            <li>DAMAGES RESULTING FROM YOUR RELIANCE ON AI-GENERATED CONTENT</li>
          </ul>

          <p className="text-sm italic">
            Some jurisdictions do not allow exclusion of implied warranties or limitation of liability for incidental damages. In such jurisdictions, OpsCel&apos;s liability is limited to the maximum extent permitted by law.
          </p>

          <p>
            <strong>13.5 Critical Applications:</strong> The Service is NOT designed for use in life-critical applications (medical devices, nuclear facilities, aircraft navigation). You use the Service for such purposes entirely at your own risk.
          </p>
        </div>
      </section>

      {/* 14. Indemnification */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">14. Indemnification</h2>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>14.1 Your Indemnity:</strong> You agree to indemnify, defend, and hold harmless OpsCel, its directors, officers, employees, and agents from and against any claims, liabilities, damages, losses, costs, or expenses (including legal fees) arising from:
          </p>
          <ul className="list-disc list-inside ml-6 space-y-2">
            <li>Your use or misuse of the Service</li>
            <li>Your breach of this EULA or violation of applicable laws</li>
            <li>Your Customer Data, including any infringement of third-party intellectual property rights</li>
            <li>Your violation of the Acceptable Use Policy</li>
            <li>Disputes between you and your customers, employees, or contractors arising from Service use</li>
          </ul>

          <p>
            <strong>14.2 OpsCel&apos;s Defence Rights:</strong> OpsCel reserves the right to assume exclusive defence and control of any matter subject to indemnification by you, in which case you will cooperate with OpsCel in asserting any available defences.
          </p>
        </div>
      </section>

      {/* 15. Governing Law */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">15. Governing Law & Dispute Resolution</h2>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>15.1 Governing Law:</strong> This EULA is governed by and construed in accordance with the laws of England and Wales, without regard to conflict of law principles.
          </p>

          <p>
            <strong>15.2 Jurisdiction:</strong> Any disputes arising from this EULA or your use of the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>

          <p>
            <strong>15.3 Dispute Resolution:</strong> Before initiating legal proceedings, the parties agree to attempt to resolve disputes through good-faith negotiation. Contact <a href="mailto:privacy@opscel.com" className="text-secondary hover:underline">privacy@opscel.com</a> to initiate dispute resolution.
          </p>
        </div>
      </section>

      {/* 16. General Provisions */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">16. General Provisions</h2>

        <div className="space-y-4 text-foreground-accent">
          <p>
            <strong>16.1 Entire Agreement:</strong> This EULA, together with our Privacy Policy and any additional terms referenced herein, constitutes the entire agreement between you and OpsCel regarding the Service and supersedes all prior agreements and understandings.
          </p>

          <p>
            <strong>16.2 Amendments:</strong> OpsCel may modify this EULA at any time by posting an updated version at <a href="https://www.opscel.com/eula" className="text-secondary hover:underline">www.opscel.com/eula</a>. Material changes will be notified via email 30 days before taking effect. Continued use after changes take effect constitutes acceptance.
          </p>

          <p>
            <strong>16.3 Severability:</strong> If any provision of this EULA is found to be invalid or unenforceable, the remaining provisions remain in full force and effect.
          </p>

          <p>
            <strong>16.4 Waiver:</strong> Failure by OpsCel to enforce any provision of this EULA does not constitute a waiver of that provision or any other provision.
          </p>

          <p>
            <strong>16.5 Assignment:</strong> You may not assign or transfer this EULA or your Account without OpsCel&apos;s prior written consent. OpsCel may assign this EULA to any successor or affiliate without your consent.
          </p>

          <p>
            <strong>16.6 Force Majeure:</strong> OpsCel is not liable for delays or failures in performance resulting from causes beyond our reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, labour disputes, or government actions.
          </p>

          <p>
            <strong>16.7 Export Compliance:</strong> You agree to comply with all applicable export and import laws and regulations. You may not use the Service in countries subject to trade sanctions or embargoes.
          </p>

          <p>
            <strong>16.8 Independent Contractors:</strong> This EULA does not create a partnership, joint venture, employment, or agency relationship between you and OpsCel.
          </p>
        </div>
      </section>

      {/* Contact */}
      <section className="mb-10">
        <h2 className="text-2xl font-heading font-bold text-foreground mb-4">17. Contact Information</h2>

        <div className="space-y-3 text-foreground-accent">
          <p>If you have questions about this EULA, please contact us:</p>

          <div className="bg-muted p-6 rounded-lg">
            <p className="font-semibold mb-2">Opscel Ltd</p>
            <p>Company Number: {companyDetails.companiesHouseNumber}</p>
            <p>Registered in England and Wales</p>
            <p className="mt-4">
              <strong>General enquiries:</strong> <a href="mailto:hello@opscel.com" className="text-secondary hover:underline">hello@opscel.com</a>
            </p>
            <p>
              <strong>Support:</strong> <a href="mailto:support@opscel.com" className="text-secondary hover:underline">support@opscel.com</a>
            </p>
            <p>
              <strong>Legal/Privacy:</strong> <a href="mailto:privacy@opscel.com" className="text-secondary hover:underline">privacy@opscel.com</a>
            </p>
          </div>
        </div>
      </section>

      {/* Acknowledgement */}
      <div className="bg-blue-50 border-l-4 border-blue-500 p-6 rounded-r-lg">
        <p className="text-blue-900 font-semibold mb-2">By using OpsCel, you acknowledge that:</p>
        <ul className="list-disc list-inside space-y-2 text-blue-800 ml-4">
          <li>You have read and understood this EULA</li>
          <li>You agree to be bound by its terms</li>
          <li>You have authority to enter into this agreement on behalf of your business</li>
          <li>This EULA may be updated from time to time with notice</li>
        </ul>
        <p className="text-blue-800 mt-4 text-sm">
          <strong>Last updated:</strong> 24 May 2026
        </p>
      </div>
    </LegalPage>
  );
};

export default EULAPage;
